name: jaspr_notifier
description: Jaspr state management with MVVM-inspired ViewModels & Notifiers. Port of reactive_notifier for Jaspr framework.

version: 1.0.0
homepage: https://github.com/JhonaCodes/jaspr_notifier.git
repository: https://github.com/JhonaCodes/jaspr_notifier.git
issue_tracker: https://github.com/JhonaCodes/jaspr_notifier/issues

topics:
  - jaspr
  - state-management
  - reactive
  - state
  - mvvm

environment:
  sdk: ^3.10.0

dependencies:
  jaspr: ^0.22.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  jaspr_test: ^0.22.0
  jaspr_builder: ^0.22.0
